name: rapids-25.04
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - mne
  - black
  - flake8
  - isort
  - seaborn
  - ipykernel
  - mne
  - mne-features
  - pip:
    - python-dotenv
    - mkdocs
    - -e .